// examples/vue/two-way-streaming-vue/src/TwoWayStreamingApp.vue
<template>
  <div id="app">
    <div class="container">
      <h2 class="text-danger">{{ apiFailed }}</h2>
      <div class="row col-sm-12">
        <h2 class="text-center">Two-way Streaming in Vue</h2>
      </div>
      <div class="row col-sm-12" style="margin-top: 20px;">
        <div class="col-sm-6">
          <div class="text-center text-muted">Local</div>
          <div class="fp-Video">
            <div id="localVideo" class="display"></div>
          </div>
          <div class="input-group col-sm-5" style="margin: 10px auto 0 auto;">
            <input type="text" 
             class="form-control"
             placeholder="Stream Name"
             v-model="publishStreamName"
             :disabled="publishStreamNameDisabled"
            />
            <div class="input-group-btn">
              <button
               class="btn btn-outline-dark"
               :disabled="publishButtonDisabled"
               v-on:click="onPublishClick">
                {{ publishButtonText }}
              </button>
            </div>
          </div>
          <div class="text-center" style="margin-top: 20px;">
            <div v-bind:class="publishStatusClass">{{ publishStatus }}</div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="text-center text-muted">Remote</div>
          <div class="fp-Video">
            <div id="remoteVideo" class="display"></div>
          </div>
          <div class="input-group col-sm-5" style="margin: 10px auto 0 auto;">
            <input type="text" 
             class="form-control"
             placeholder="Stream Name"
             v-model="playStreamName"
             :disabled="playStreamNameDisabled"
            />
            <div class="input-group-btn">
              <button
               class="btn btn-outline-dark"
               :disabled="playButtonDisabled"
               v-on:click="onPlayClick">
                {{ playButtonText }}
              </button>
            </div>
          </div>
          <div class="text-center" style="margin-top: 20px;">
            <div v-bind:class="playStatusClass">{{ playStatus }}</div>
          </div>
        </div>
      </div>
      <div class="row col-sm-12" style="margin-top: 20px;">
          <div class="col-sm-6 offset-sm-3">
            <div class="input-group col-sm-5">
              <input type="text"
               class="form-control"
               placeholder="Server Url"
               v-model="serverUrl"
               :disabled="serverUrlDisabled"
              />
              <div class="input-group-btn">
                <button
                 class="btn btn-outline-dark"
                 :disabled="connectButtonDisabled"
                 v-on:click="onConnectClick">
                  {{ connectButtonText }}
                </button>
              </div>
            </div>
            <div class="text-center" style="margin-top: '20px';">
              <div v-bind:class="sessionStatusClass">{{ sessionStatus }}</div>
            </div>
          </div>
      </div>
    </div>
  </div>
</template>

<script>
import * as FPUtils from './fp-utils.js';
import * as Flashphoner from '@flashphoner/websdk';

const SESSION_STATUS = Flashphoner.constants.SESSION_STATUS;
const STREAM_STATUS = Flashphoner.constants.STREAM_STATUS;
const Browser = Flashphoner.Browser;
const PRELOADER_URL = require('@/assets/media/preloader.mp4');

export default {
  name: 'TwoWayStreamingApp',
  data: () => ({
    apiFailed: '',
    session: null,
    sessionStatus: '',
    sessionStatusClass: 'text-muted',
    localVideo: null,
    remoteVideo: null,
    publishStreamObj: null,
    publishStatus: '',
    publishStatusClass: 'text-muted',
    playStreamObj: null,
    playStatus: '',
    playStatusClass: 'text-muted',
    publishStreamName: 'streamName',
    publishStreamNameDisabled: true,
    playStreamName: 'streamName',
    playStreamNameDisabled: true,
    connectButtonText: 'Connect',
    connectButtonDisabled: false,
    serverUrl: 'wss://demo.flashphoner.com:8443',
    serverUrlDisabled: false,
    publishButtonText: 'Publish',
    publishButtonDisabled: true,
    playButtonText: 'Play',
    playButtonDisabled: true,
  }),
  mounted() {
    this.onLoad();
  },
  methods: {
    onLoad() {
      try {
        Flashphoner.init({});
        this.localVideo = document.getElementById('localVideo');
        this.remoteVideo = document.getElementById('remoteVideo');
      }
      catch(e) {
        console.log(e);
        this.apiFailed = 'Your browser does not support WebRTC technology needed for this example';
        this.connectButtonDisabled = true;
        this.serverUrlDisabled = true;
      }
    },
    onConnected(session) {
      this.session = session;
      this.connectButtonText = 'Disconnect';
      this.connectButtonDisabled = false;
      this.serverUrlDisabled = true;
      this.onUnpublished();
      this.onStopped();
    },
    onDisconnected() {
      this.session = null;
      this.connectButtonText = 'Connect';
      this.connectButtonDisabled = false;
      this.serverUrlDisabled = false;
      this.onUnpublished();
      this.onStopped();
    },
    onPublishing(stream) {
      this.publishStreamObj = stream;
      this.publishButtonText = 'Unpublish';
      this.publishButtonDisabled = false;
    },
    onUnpublished() {
      let session = this.session;
      let itemState = true;

      if(session && session.status() === SESSION_STATUS.ESTABLISHED) {
        itemState = false;
      }
      this.publishStreamObj = null;
      this.publishButtonText = 'Publish';
      this.publishButtonDisabled = itemState;
      this.publishStreamNameDisabled = itemState;
    },
    onPlaying(stream) {
      this.playStreamObj = stream;
      this.playButtonText = 'Stop';
      this.playButtonDisabled = false;
    },
    onStopped() {
      let session = this.session;
      let itemState = true;

      if(session && session.status() === SESSION_STATUS.ESTABLISHED) {
        itemState = false;
      }
      this.playStreamObj = null;
      this.playButtonText = 'Play';
      this.playButtonDisabled = itemState;
      this.playStreamNameDisabled = itemState;
    },
    publishStream() {
      let session = this.session;
      let streamName = this.publishStreamName;
      let localVideo = this.localVideo;

      if(session && localVideo) {
        session.createStream({
          name: streamName,
          display: localVideo,
          cacheLocalResources: true,
          receiveVideo: false,
          receiveAudio: false
        }).on(STREAM_STATUS.PUBLISHING, (stream) => {
          this.publishStatus = STREAM_STATUS.PUBLISHING;
          this.publishStatusClass = 'text-success';
          this.onPublishing(stream);
        }).on(STREAM_STATUS.UNPUBLISHED, () => {
          this.publishStatus = STREAM_STATUS.UNPUBLISHED;
          this.publishStatusClass = 'text-success';
          this.onUnpublished();
        }).on(STREAM_STATUS.FAILED, () => {
          this.publishStatus = STREAM_STATUS.FAILED;
          this.publishStatusClass = 'text-danger';
          this.onUnpublished();
        }).publish();
      }
    },
    playStream() {
      let session = this.session;
      let streamName = this.playStreamName;
      let remoteVideo = this.remoteVideo;

      if(session && remoteVideo) {
        session.createStream({
          name: streamName,
          display: remoteVideo
        }).on(STREAM_STATUS.PENDING, (stream) => {
          let video = document.getElementById(stream.id());
          if (!video.hasListeners) {
            video.hasListeners = true;
            video.addEventListener('resize', (event) => {
                FPUtils.resizeVideo(event.target);
            });
          }
        }).on(STREAM_STATUS.PLAYING, (stream) => {
          this.playStatus = STREAM_STATUS.PLAYING;
          this.playStatusClass = 'text-success';
          this.onPlaying(stream);
        }).on(STREAM_STATUS.STOPPED, () => {
          this.playStatus = STREAM_STATUS.STOPPED;
          this.playStatusClass = 'text-success';
          this.onStopped();
        }).on(STREAM_STATUS.FAILED, () => {
          this.playStatus = STREAM_STATUS.FAILED;
          this.playStatusClass = 'text-danger';
          this.onStopped();
        }).play();
      }
    },
    onConnectClick() {
      let url = this.serverUrl;
      let session = this.session;

      if (!session) {
        console.log("Create new session with url " + url);
        this.connectButtonDisabled = true;
        this.serverUrlDisabled = true;
        Flashphoner.createSession({urlServer: url}).on(SESSION_STATUS.ESTABLISHED, (session) => {
          this.sessionStatus = SESSION_STATUS.ESTABLISHED;
          this.sessionStatusClass = 'text-success';
          this.onConnected(session);
        }).on(SESSION_STATUS.DISCONNECTED, () => {
          this.sessionStatus = SESSION_STATUS.DISCONNECTED;
          this.sessionStatusClass = 'text-success';
          this.onDisconnected();
        }).on(SESSION_STATUS.FAILED, () => {
          this.sessionStatus = SESSION_STATUS.FAILED;
          this.sessionStatusClass = 'text-danger';
          this.onDisconnected();
        });
      } else {
        this.connectButtonDisabled = true;
        session.disconnect();
      }
    },
    onPublishClick() {
      let stream = this.publishStreamObj;
      let localVideo = this.localVideo;

      if (!localVideo) return;
      if (!stream) {
        this.publishButtonDisabled = true;
        this.publishStreamNameDisabled = true;
        if (Browser.isSafariWebRTC()) {
          Flashphoner.playFirstVideo(localVideo, true, PRELOADER_URL).then(() => {
            this.publishStream();
          });
          return;
        }
        this.publishStream();
      } else {
        this.publishButtonDisabled = true;
        stream.stop();
      }
    },
    onPlayClick() {
      let stream = this.playStreamObj;
      let remoteVideo = this.remoteVideo;

      if (!remoteVideo) return;
      if (!stream) {
        this.playButtonDisabled = true;
        this.playStreamNameDisabled = true;
        if (Flashphoner.getMediaProviders()[0] === "WSPlayer") {
          Flashphoner.playFirstSound();
        } else if (Browser.isSafariWebRTC()) {
          Flashphoner.playFirstVideo(remoteVideo, false, PRELOADER_URL).then(() => {
            this.playStream();
          });
          return;
        }
        this.playStream();
      } else {
        this.playButtonDisabled = true;
        stream.stop();
      }
    }
  }
}
</script>

<style>
.fp-Video {
    border: 1px double black;
    width: 322px;
    height: 242px;
    text-align: center;
    background: #c0c0c0;
    margin: 0 auto 0 auto;
}

.display {
    width: 100%;
    height: 100%;
    display: inline-block;
}

.display > video, object {
    width: 100%;
    height: 100%;
}

video:-webkit-full-screen {
    border-radius: 1px;
}
</style>

// examples/typescript/two-way-streaming-ts/src/TwoWayStreamingApp.tsx
import React, { Component } from 'react';
import './TwoWayStreamingApp.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import * as FPUtils from './fp-utils';
import * as Flashphoner from '@flashphoner/websdk';

const SESSION_STATUS = Flashphoner.constants.SESSION_STATUS;
const STREAM_STATUS = Flashphoner.constants.STREAM_STATUS;
const Browser = Flashphoner.Browser;
const PRELOADER_URL = process.env.PUBLIC_URL + '/media/preloader.mp4';

interface TwoWayStreamingState {
  apiFailed: string,
  session: any,
  sessionStatus: string,
  sessionStatusClass: string,
  localVideo: any,
  remoteVideo: any,
  publishStream: any,
  publishStatus: string,
  publishStatusClass: string,
  playStream: any,
  playStatus: string,
  playStatusClass: string,
  publishStreamName: string,
  publishStreamNameDisabled: boolean,
  playStreamName: string,
  playStreamNameDisabled: boolean,
  connectButtonText: string,
  connectButtonDisabled: boolean,
  serverUrl: string,
  serverUrlDisabled: boolean,
  publishButtonText: string,
  publishButtonDisabled: boolean,
  playButtonText: string,
  playButtonDisabled: boolean
}

class TwoWayStreamingApp extends Component<{}, TwoWayStreamingState> {
  constructor(props: any) {
    super(props);
    this.state = {
      apiFailed: '',
      session: null,
      sessionStatus: '',
      sessionStatusClass: 'text-muted',
      localVideo: null,
      remoteVideo: null,
      publishStream: null,
      publishStatus: '',
      publishStatusClass: 'text-muted',
      playStream: null,
      playStatus: '',
      playStatusClass: 'text-muted',
      publishStreamName: 'streamName',
      publishStreamNameDisabled: true,
      playStreamName: 'streamName',
      playStreamNameDisabled: true,
      connectButtonText: 'Connect',
      connectButtonDisabled: false,
      serverUrl: 'wss://demo.flashphoner.com:8443',
      serverUrlDisabled: false,
      publishButtonText: 'Publish',
      publishButtonDisabled: true,
      playButtonText: 'Play',
      playButtonDisabled: true
    };
  }

  componentDidMount() {
    try {
      Flashphoner.init({});
      this.setState({
        localVideo: document.getElementById('localVideo'),
        remoteVideo: document.getElementById('remoteVideo')
      });
    }
    catch(e) {
      console.log(e);
      this.setState({
        apiFailed: 'Your browser does not support WebRTC technology needed for this example',
        connectButtonDisabled: true,
        serverUrlDisabled: true
      });
    }
  }

  onConnected = (session: any) => {
    this.setState({
      session: session,
      connectButtonText: 'Disconnect',
      connectButtonDisabled: false,
      serverUrlDisabled: true
    });
    this.onUnpublished();
    this.onStopped();
  }

  onDisconnected = () => {
    this.setState({
      session: null,
      connectButtonText: 'Connect',
      connectButtonDisabled: false,
      serverUrlDisabled: false
    });
    this.onUnpublished();
    this.onStopped();
  }

  onPublishing = (stream: any) => {
    this.setState({
      publishStream: stream,
      publishButtonText: 'Unpublish',
      publishButtonDisabled: false
    });
  }

  onUnpublished = () => {
    let session = this.state.session;
    let itemState = true;

    if(session && session.status() === SESSION_STATUS.ESTABLISHED) {
      itemState = false;
    }
    this.setState({
      publishStream: null,
      publishButtonText: 'Publish',
      publishButtonDisabled: itemState,
      publishStreamNameDisabled: itemState
    });
  }

  onPlaying = (stream: any) => {
    this.setState({
      playStream: stream,
      playButtonText: 'Stop',
      playButtonDisabled: false
    });
  }

  onStopped = () => {
    let session = this.state.session;
    let itemState = true;

    if(session && session.status() === SESSION_STATUS.ESTABLISHED) {
      itemState = false;
    }
    this.setState({
      playStream: null,
      playButtonText: 'Play',
      playButtonDisabled: itemState,
      playStreamNameDisabled: itemState
    });
  }

  publishStream = () => {
    let app = this;
    let session = this.state.session;
    let streamName = this.state.publishStreamName;
    let localVideo = this.state.localVideo;

    if(session && localVideo) {
      session.createStream({
        name: streamName,
        display: localVideo,
        cacheLocalResources: true,
        receiveVideo: false,
        receiveAudio: false
      }).on(STREAM_STATUS.PUBLISHING, (stream: any) => {
        app.setState({publishStatus: STREAM_STATUS.PUBLISHING, publishStatusClass: 'text-success'});
        app.onPublishing(stream);
      }).on(STREAM_STATUS.UNPUBLISHED, () => {
        app.setState({publishStatus: STREAM_STATUS.UNPUBLISHED, publishStatusClass: 'text-success'});
        app.onUnpublished();
      }).on(STREAM_STATUS.FAILED, () => {
        app.setState({publishStatus: STREAM_STATUS.FAILED, publishStatusClass: 'text-danger'});
        app.onUnpublished();
      }).publish();
    }
  }

  playStream = () => {
    let app = this;
    let session = this.state.session;
    let streamName = this.state.playStreamName;
    let remoteVideo = this.state.remoteVideo;

    if(session && remoteVideo) {
      session.createStream({
        name: streamName,
        display: remoteVideo
      }).on(STREAM_STATUS.PENDING, (stream: any) => {
        let video: any = document.getElementById(stream.id());
        if (!video.hasListeners) {
            video.hasListeners = true;
            video.addEventListener('resize', (event: any) => {
                FPUtils.resizeVideo(event.target);
            });
        }
      }).on(STREAM_STATUS.PLAYING, (stream: any) => {
        app.setState({playStatus: STREAM_STATUS.PLAYING, playStatusClass: 'text-success'});
        app.onPlaying(stream);
      }).on(STREAM_STATUS.STOPPED, () => {
        app.setState({playStatus: STREAM_STATUS.STOPPED, playStatusClass: 'text-success'});
        app.onStopped();
      }).on(STREAM_STATUS.FAILED, () => {
        app.setState({playStatus: STREAM_STATUS.FAILED, playStatusClass: 'text-danger'});
        app.onStopped();
      }).play();
    }
  }

  onConnectClick = () => {
    let app = this;
    let url = this.state.serverUrl;
    let session = this.state.session;

    if (!session) {
      console.log("Create new session with url " + url);
      app.setState({connectButtonDisabled: true, serverUrlDisabled: true});
      Flashphoner.createSession({urlServer: url}).on(SESSION_STATUS.ESTABLISHED, (session: any) => {
        app.setState({sessionStatus: SESSION_STATUS.ESTABLISHED, sessionStatusClass: 'text-success'});
        app.onConnected(session);
      }).on(SESSION_STATUS.DISCONNECTED, () => {
        app.setState({sessionStatus: SESSION_STATUS.DISCONNECTED, sessionStatusClass: 'text-success'});
        app.onDisconnected();
      }).on(SESSION_STATUS.FAILED, () => {
        app.setState({sessionStatus: SESSION_STATUS.FAILED, sessionStatusClass: 'text-danger'});
        app.onDisconnected();
      });
    } else {
      app.setState({connectButtonDisabled: true});
      session.disconnect();
    }
  }

  onPublishClick = () => {
    let app = this;
    let stream = this.state.publishStream;
    let localVideo = this.state.localVideo;

    if (!localVideo) return;
    if (!stream) {
      app.setState({publishButtonDisabled: true, publishStreamNameDisabled: true});
      if (Browser.isSafariWebRTC()) {
        Flashphoner.playFirstVideo(localVideo, true, PRELOADER_URL).then(() => {
            app.publishStream();
        });
        return;
      }
      app.publishStream();
    } else {
      app.setState({publishButtonDisabled: true});
      stream.stop();
    }
  }

  onPlayClick = () => {
    let app = this;
    let stream = this.state.playStream;
    let remoteVideo = this.state.remoteVideo;

    if (!remoteVideo) return;
    if (!stream) {
      app.setState({playButtonDisabled: true, playStreamNameDisabled: true});
      if (Flashphoner.getMediaProviders()[0] === "WSPlayer") {
        Flashphoner.playFirstSound();
      } else if (Browser.isSafariWebRTC()) {
        Flashphoner.playFirstVideo(remoteVideo, false, PRELOADER_URL).then(() => {
            app.playStream();
        });
        return;
      }
      app.playStream();
    } else {
      app.setState({playButtonDisabled: true});
      stream.stop();
    }
  }

  render() {
    return (
      <div className="container">
        <h2 className="text-danger">{this.state.apiFailed}</h2>
        <div className="row">
          <h2 className="text-center">Two-way Streaming in Typescript</h2>
        </div>
        <div className="row row-space">
          <div className="col-sm-6">
            <div className="text-center text-muted">Local</div>
            <div className="fp-Video">
              <div id="localVideo" className="display"></div>
            </div>
            <div className="input-group col-sm-5" style={{margin: '10px auto 0 auto'}}>
              <input type="text" 
               className="form-control"
               placeholder="Stream Name"
               value={this.state.publishStreamName}
               disabled={this.state.publishStreamNameDisabled}
               onChange={(event) => this.setState({publishStreamName: event.target.value})}
              />
              <div className="input-group-btn">
                <button
                 className="btn btn-outline-dark"
                 disabled={this.state.publishButtonDisabled}
                 onClick={() => this.onPublishClick()}>
                  {this.state.publishButtonText}
                </button>
              </div>
            </div>
            <div className="text-center" style={{marginTop: '20px'}}>
              <div className={this.state.publishStatusClass}>{this.state.publishStatus}</div>
            </div>
          </div>
          <div className="col-sm-6">
            <div className="text-center text-muted">Remote</div>
            <div className="fp-Video">
              <div id="remoteVideo" className="display"></div>
            </div>
            <div className="input-group col-sm-5" style={{margin: '10px auto 0 auto'}}>
              <input type="text" 
               className="form-control"
               placeholder="Stream Name"
               value={this.state.playStreamName}
               disabled={this.state.playStreamNameDisabled}
               onChange={(event) => this.setState({playStreamName: event.target.value})}
              />
              <div className="input-group-btn">
                <button
                 className="btn btn-outline-dark"
                 disabled={this.state.playButtonDisabled}
                 onClick={() => this.onPlayClick()}>
                  {this.state.playButtonText}
                </button>
              </div>
            </div>
            <div className="text-center" style={{marginTop: '20px'}}>
              <div className={this.state.playStatusClass}>{this.state.playStatus}</div>
            </div>
          </div>
        </div>
        <div className="row row-space">
            <div className="col-sm-6 offset-sm-3">
              <div className="input-group col-sm-5">
                <input type="text"
                 className="form-control"
                 placeholder="Server Url"
                 value={this.state.serverUrl}
                 disabled={this.state.serverUrlDisabled}
                 onChange={(event) => this.setState({serverUrl: event.target.value})}
                />
                <div className="input-group-btn">
                  <button
                   className="btn btn-outline-dark"
                   disabled={this.state.connectButtonDisabled}
                   onClick={() => this.onConnectClick()}>
                    {this.state.connectButtonText}
                  </button>
                </div>
              </div>
              <div className="text-center" style={{marginTop: '20px'}}>
                <div className={this.state.sessionStatusClass}>{this.state.sessionStatus}</div>
              </div>
            </div>
        </div>
      </div>
    );
  };
}

export default TwoWayStreamingApp;
